### ISSUE TITLE
Dude, please contunie make your client!

### ISSUE THREAD

**Issue by Xuker228** [autumnblazey/better-zoom#1]
I think no one care about github remaked software, and maybe if they try to delete you repo from zoom offcicial request just give them fake deletion and save this for all world. And original zoom client is really shitty, I agree. My email for contact, if you want to letter me when finish projokt, [i got the email]

**Comment by autumnblazey** [comment]
Removed the email so that people can't spam you, but I saved it. Yea, when I have time again I plan on continuing
